export const languages = [
  { code: 'en', label: 'English' },
  { code: 'ja', label: 'Japanese' },
  { code: 'zh', label: 'Chinese' },
  { code: 'fr', label: 'French' },
  { code: 'es', label: 'Spanish' }
];

const commonValues = {
  budget: {
    entry: { en: 'Entry', ja: 'エントリー', zh: '入门', fr: 'Entrée', es: 'Inicial' },
    standard: { en: 'Standard', ja: 'スタンダード', zh: '标准', fr: 'Standard', es: 'Estándar' },
    premium: { en: 'Premium', ja: 'プレミアム', zh: '高级', fr: 'Premium', es: 'Premium' },
    signature: { en: 'Signature', ja: 'シグネチャー', zh: '招牌', fr: 'Signature', es: 'Signature' },
    bespoke: { en: 'Bespoke', ja: '特注相談', zh: '定制咨询', fr: 'Sur mesure', es: 'A medida' }
  },
  useCase: {
    mainPlate: { en: 'Main Plate', ja: 'メイン皿', zh: '主菜盘', fr: 'Assiette principale', es: 'Plato principal' },
    sushiPlate: { en: 'Sushi Plate', ja: '寿司皿', zh: '寿司盘', fr: 'Assiette à sushi', es: 'Plato de sushi' },
    appetizer: { en: 'Appetizer', ja: '前菜皿', zh: '前菜盘', fr: 'Entrée', es: 'Aperitivo' },
    kaiseki: { en: 'Kaiseki Course', ja: '懐石コース', zh: '怀石套餐', fr: 'Menu kaiseki', es: 'Menú kaiseki' },
    sakeWare: { en: 'Sake Ware', ja: '酒器', zh: '清酒器', fr: 'Service à saké', es: 'Servicio de sake' },
    hotelDining: { en: 'Hotel Dining', ja: 'ホテルダイニング', zh: '酒店餐饮', fr: 'Restauration hôtelière', es: 'Restaurante de hotel' },
    courseMenu: { en: 'Course Menu', ja: 'コース料理', zh: '套餐菜单', fr: 'Menu dégustation', es: 'Menú degustación' },
    breakfast: { en: 'Hotel Breakfast', ja: 'ホテル朝食', zh: '酒店早餐', fr: 'Petit-déjeuner hôtelier', es: 'Desayuno de hotel' },
    privateDining: { en: 'Private Dining', ja: '個室・特別席', zh: '私人包间', fr: 'Salon privé', es: 'Comedor privado' }
  },
  cuisine: {
    sushi: { en: 'Sushi', ja: '寿司', zh: '寿司', fr: 'Sushi', es: 'Sushi' },
    kaiseki: { en: 'Kaiseki', ja: '懐石', zh: '怀石', fr: 'Kaiseki', es: 'Kaiseki' },
    wagyu: { en: 'Wagyu / Steak', ja: '和牛・ステーキ', zh: '和牛 / 牛排', fr: 'Wagyu / Steak', es: 'Wagyu / Steak' },
    seafood: { en: 'Seafood', ja: '魚介', zh: '海鲜', fr: 'Fruits de mer', es: 'Mariscos' },
    dessert: { en: 'Dessert', ja: 'デザート', zh: '甜点', fr: 'Dessert', es: 'Postre' },
    sakePairing: { en: 'Tea / Sake Pairing', ja: '茶・酒ペアリング', zh: '茶 / 清酒搭配', fr: 'Accord thé / saké', es: 'Maridaje té / sake' },
    hotelDining: { en: 'Hotel Dining', ja: 'ホテルダイニング', zh: '酒店餐饮', fr: 'Restauration hôtelière', es: 'Hotel dining' }
  },
  size: {
    small: { en: 'Small', ja: '小', zh: '小', fr: 'Petit', es: 'Pequeño' },
    medium: { en: 'Medium', ja: '中', zh: '中', fr: 'Moyen', es: 'Mediano' },
    large: { en: 'Large', ja: '大', zh: '大', fr: 'Grand', es: 'Grande' },
    extraLarge: { en: 'Extra Large', ja: '特大', zh: '特大', fr: 'Très grand', es: 'Extra grande' }
  },
  tone: {
    white: { en: 'White', ja: '白', zh: '白色', fr: 'Blanc', es: 'Blanco' },
    blue: { en: 'Blue', ja: '青', zh: '蓝色', fr: 'Bleu', es: 'Azul' },
    black: { en: 'Black', ja: '黒', zh: '黑色', fr: 'Noir', es: 'Negro' },
    earth: { en: 'Earth Tone', ja: '土色', zh: '大地色', fr: 'Tons terre', es: 'Tono tierra' },
    gold: { en: 'Gold Accent', ja: '金彩', zh: '金色点缀', fr: 'Accent or', es: 'Acento dorado' }
  },
  buyerType: {
    restaurantOwner: { en: 'Restaurant Owner', ja: 'レストランオーナー', zh: '餐厅业主', fr: 'Propriétaire de restaurant', es: 'Dueño de restaurante' },
    hotel: { en: 'Hotel', ja: 'ホテル', zh: '酒店', fr: 'Hôtel', es: 'Hotel' },
    distributor: { en: 'Distributor', ja: '販売代理店', zh: '经销商', fr: 'Distributeur', es: 'Distribuidor' },
    procurement: { en: 'Interior / Procurement', ja: '内装・購買', zh: '室内设计 / 采购', fr: 'Design / Achats', es: 'Interiorismo / Compras' }
  }
};

function expandValueGroup(group) {
  const out = { en: {}, ja: {}, zh: {}, fr: {}, es: {} };
  Object.entries(group).forEach(([key, labels]) => {
    Object.keys(out).forEach((lang) => {
      out[lang][key] = labels[lang];
    });
  });
  return out;
}

const valueLabels = Object.fromEntries(
  Object.entries(commonValues).map(([group, values]) => [group, expandValueGroup(values)])
);

export const translations = {
  en: {
    nav: { home: 'Home', useCase: 'Use Case', budget: 'Budget', cuisine: 'Cuisine', collection: 'Collection', consultation: 'Consultation', sampleRequest: 'Sample Request', faq: 'FAQ', contact: 'Contact' },
    cta: { requestCatalog: 'Request Catalog', selectionList: 'Selection List', browseBudget: 'Browse by Budget', chooseUseCase: 'Choose by Use Case', requestB2B: 'Request B2B Catalog', viewDetails: 'View Details', quickView: 'Quick View', addToQuote: 'Add to Quote Cart', askSample: 'Ask for Sample', requestQuote: 'Request Quote', discussItems: 'Discuss These Items', fullSelection: 'View Full Selection List', clearAll: 'Clear all', submit: 'Submit Request', startBudget: 'Browse by Budget', startUseCase: 'Browse by Use Case', catalog: 'Request Catalog', discussConcept: 'Discuss Your Restaurant Concept', budgetRecommendation: 'Get Budget-Based Recommendation' },
    hero: { kicker: 'Premium Arita ware for restaurant owners', title: 'Choose Arita Ware by Budget, Cuisine, and Restaurant Concept.', subtitle: 'Premium Japanese tableware curated for restaurant owners who want to elevate plating, guest perception, and brand value.', trust1: 'For Sushi / Kaiseki / Fine Dining / Hotels', trust2: 'Sample consultation available', trust3: 'Wholesale and repeat orders supported' },
    sections: { choose: 'Choose by what matters to your restaurant', chooseText: 'Start with budget, use case, cuisine, or the atmosphere you want guests to remember.', useCase: 'Browse by Use Case', budget: 'Browse by Budget', cuisine: 'Browse by Cuisine', featured: 'Featured restaurant-ready pieces', challenges: 'What restaurant owners need to know before choosing tableware.', value: 'Why tableware changes the restaurant experience', contact: 'Start with a catalog, sample, or quote conversation', collection: 'Collection', related: 'Related Products' },
    cards: { match: 'Will it match our cuisine and concept?', premium: 'Will it make our dishes look more premium?', reorder: 'Can we reorder with confidence?', samples: 'How do samples, MOQ, and shipping work?', authentic: 'Is the story authentic enough for our brand?', matchText: 'Find pieces suited to sushi, kaiseki, hotels, tasting menus, or private dining.', premiumText: 'Use negative space, color, and height to make each dish feel more valuable.', reorderText: 'Plan for repeat orders, new branches, and stable operational sourcing.', samplesText: 'Clarify samples, minimum quantities, shipping, and lead times before buying.', authenticText: 'Bring the craft story of Arita ware into your restaurant brand.' },
    values: { value1: 'Make each dish look more valuable.', value1Text: 'Select tableware that raises the perceived value of the plate.', value2: 'Strengthen the restaurant brand.', value2Text: 'Create a consistent world view across menu, service, and dining room.', value3: 'Source with confidence.', value3Text: 'Discuss samples, MOQ, international shipping, and repeat orders before committing.' },
    product: { bestFor: 'Best for', moq: 'MOQ', sample: 'Sample', sampleAvailable: 'Available', sampleRequested: 'Sample requested', consultation: 'Consultation available', size: 'Size', kiln: 'Kiln / Origin', price: 'Price range', useCase: 'Use case', cuisine: 'Cuisine', scene: 'Recommended scene', shipping: 'International shipping consultation', yes: 'Yes', quantity: 'Quantity', unitPrice: 'Estimated unit price', estimatedTotal: 'Estimated total', totalRange: 'Estimated Budget Range', remove: 'Remove', qty: 'Qty', added: 'Added', addedNotice: 'added to your quote cart.' },
    filter: { title: 'Filter', active: 'Active filters', budget: 'Budget', useCase: 'Use Case', cuisine: 'Cuisine', size: 'Size', tone: 'Color / Tone', buyerType: 'Buyer Type', sampleAvailable: 'Sample Available', moqRange: 'MOQ Range', upTo12: 'Up to 12 pieces', upTo24: 'Up to 24 pieces', upTo48: 'Up to 48 pieces', sort: 'Sort by', recommended: 'Recommended', priceLow: 'Price: Low to High', priceHigh: 'Price: High to Low', bestSushi: 'Best for Sushi', bestKaiseki: 'Best for Kaiseki', sampleSort: 'Sample Available', premiumSort: 'Premium Collection', results: 'results' },
    cart: { empty: 'Your selection list is empty.', emptyText: 'Start by choosing tableware based on your restaurant’s budget, cuisine, or use case.', title: 'Selection List', subtitle: 'Save items, adjust quantities, request samples, and prepare a quote.', drawerTitle: 'Your Selection List', subtotal: 'Estimated budget' },
    form: { name: 'Name', company: 'Restaurant / Company Name', country: 'Country / Region', restaurantType: 'Restaurant Type', cuisine: 'Cuisine', budget: 'Approximate Budget per Piece', quantity: 'Quantity Range', selectedItems: 'Selected Items', sampleRequest: 'Sample Request', message: 'Message', concept: 'Restaurant Concept', spend: 'Average Guest Spend', opening: 'Opening / Buying Timeline', submitSuccess: 'Thank you. Your request has been prepared. Our team will review your selected items and contact you shortly.' },
    page: { budgetTitle: 'Browse by Budget', budgetText: 'Select a price range and see where each tier works best operationally.', useCaseTitle: 'Browse by Use Case', useCaseText: 'Choose by service moment, course format, and guest experience.', cuisineTitle: 'Browse by Cuisine', cuisineText: 'Find pieces that frame sushi, kaiseki, wagyu, seafood, dessert, or sake pairing.', collectionTitle: 'Collection / Products', collectionText: 'Filter by budget, use case, cuisine, size, tone, MOQ, and sample availability.', selectionTitle: 'Selection List / Quote Cart', sampleTitle: 'Sample Request', sampleText: 'Prepare a sample request for the pieces you are considering.', consultationTitle: 'Restaurant Consultation', consultationText: 'Tell us about your concept and we will prepare a tableware direction.', contactTitle: 'Contact / Request Quote', contactText: 'Your selected items are reflected below for a quote conversation.', detailBack: 'Back to collection' },
    faq: { q1: 'Do you work with restaurants and hotels?', a1: 'Yes. This catalog is designed for restaurants, hotels, and procurement teams.', q2: 'Can we request samples?', a2: 'Yes. Use Ask for Sample or the Sample Request page to prepare your list.', q3: 'What is the MOQ?', a3: 'MOQ depends on the item and kiln. Each product card shows a starting quantity.', q4: 'Can you ship internationally?', a4: 'International shipping can be discussed during the quote process.', q5: 'Can we choose products by budget?', a5: 'Yes. Browse by Budget and filters are designed for budget-led planning.', q6: 'Can you recommend tableware based on our cuisine?', a6: 'Yes. Use Cuisine filters or the consultation page for curated recommendations.', q7: 'Do you support repeat orders?', a7: 'Repeat orders can be planned for operational consistency.', q8: 'Can we discuss custom or curated selections?', a8: 'Yes. Bespoke or curated selections can be discussed for larger projects.' },
    footer: { description: 'A B2B catalog for restaurant owners selecting Arita ware by budget, cuisine, use case, and concept.', rights: 'All rights reserved.' },
    valueLabels: { ...Object.fromEntries(Object.entries(valueLabels).map(([group, langs]) => [group, langs.en])) }
  },
  ja: {
    nav: { home: 'Home', useCase: '用途', budget: '予算', cuisine: '料理', collection: '商品一覧', consultation: '相談', sampleRequest: 'サンプル', faq: 'FAQ', contact: '問い合わせ' },
    cta: { requestCatalog: 'カタログ請求', selectionList: '選択リスト', browseBudget: '予算から選ぶ', chooseUseCase: '用途から選ぶ', requestB2B: 'B2Bカタログ請求', viewDetails: '詳細を見る', quickView: 'クイック表示', addToQuote: '見積もりリストに追加', askSample: 'サンプル相談', requestQuote: '見積もり依頼', discussItems: 'この商品で相談', fullSelection: '選択リストを見る', clearAll: 'すべて解除', submit: '送信する', startBudget: '予算から探す', startUseCase: '用途から探す', catalog: 'カタログ請求', discussConcept: '店舗コンセプトを相談', budgetRecommendation: '予算別提案を依頼' },
    hero: { kicker: 'レストランオーナー向け有田焼', title: '予算・料理・店舗コンセプトから有田焼を選ぶ。', subtitle: '料理の見え方、顧客の印象、店舗ブランドを高めたいレストランのための高級和食器カタログです。', trust1: '寿司 / 懐石 / ファインダイニング / ホテル向け', trust2: 'サンプル相談可', trust3: '卸・継続発注に対応' },
    sections: { choose: '店舗に必要な条件から選ぶ', chooseText: '予算、用途、料理ジャンル、記憶に残したい雰囲気から探せます。', useCase: '用途から選ぶ', budget: '予算から選ぶ', cuisine: '料理ジャンルから選ぶ', featured: '代表商品', challenges: '器選びの前にレストランオーナーが知るべきこと', value: '器がレストラン体験を変える理由', contact: 'カタログ・サンプル・見積もり相談を始める', collection: '商品一覧', related: '関連商品' },
    cards: { match: '料理やコンセプトに合うか？', premium: '料理をより高級に見せられるか？', reorder: '安心して継続発注できるか？', samples: 'サンプル・MOQ・配送はどうなるか？', authentic: 'ブランドにふさわしい本物のストーリーがあるか？', matchText: '寿司、懐石、ホテル、コース、個室などに合う器を探せます。', premiumText: '余白、色、立体感で料理の価値を高めます。', reorderText: '継続発注や店舗展開を見据えた調達が可能です。', samplesText: 'サンプル、最低注文数量、配送、納期を事前に確認できます。', authenticText: '有田焼の伝統と職人性を店舗ブランドに活かせます。' },
    values: { value1: '料理の価値を高く見せる。', value1Text: '一皿の印象を高める器選び。', value2: '店舗ブランドを強くする。', value2Text: 'メニュー、サービス、空間の世界観を揃えます。', value3: '安心して調達する。', value3Text: 'サンプル、MOQ、海外配送、継続発注まで相談できます。' },
    product: { bestFor: 'おすすめ', moq: 'MOQ', sample: 'サンプル', sampleAvailable: '可', sampleRequested: 'サンプル希望', consultation: '相談可', size: 'サイズ', kiln: '窯元・産地', price: '価格帯', useCase: '用途', cuisine: '料理', scene: '導入シーン', shipping: '海外配送相談', yes: '可', quantity: '数量', unitPrice: '想定単価', estimatedTotal: '想定合計', totalRange: '想定予算', remove: '削除', qty: '数量', added: '追加済み', addedNotice: 'をリストに追加しました。' },
    filter: { title: '絞り込み', active: '選択中', budget: '予算', useCase: '用途', cuisine: '料理', size: 'サイズ', tone: '色味', buyerType: '購入者タイプ', sampleAvailable: 'サンプル可', moqRange: 'MOQ', upTo12: '12枚まで', upTo24: '24枚まで', upTo48: '48枚まで', sort: '並び替え', recommended: 'おすすめ', priceLow: '価格が低い順', priceHigh: '価格が高い順', bestSushi: '寿司向け', bestKaiseki: '懐石向け', sampleSort: 'サンプル可', premiumSort: 'プレミアム', results: '件' },
    cart: { empty: '選択リストは空です。', emptyText: '予算、料理、用途から器を選び始めてください。', title: '選択リスト', subtitle: '商品を保存し、数量やサンプル希望を調整して見積もり準備ができます。', drawerTitle: '選択リスト', subtotal: '想定予算' },
    form: { name: 'お名前', company: '店舗・会社名', country: '国・地域', restaurantType: '店舗タイプ', cuisine: '料理ジャンル', budget: '1枚あたり予算', quantity: '数量目安', selectedItems: '選択商品', sampleRequest: 'サンプル希望', message: 'メッセージ', concept: '店舗コンセプト', spend: '客単価', opening: '導入時期', submitSuccess: 'ありがとうございます。選択内容を確認し、担当者よりご連絡します。' },
    page: { budgetTitle: '予算から選ぶ', budgetText: '価格帯ごとに向いている店舗や導入シーンを確認できます。', useCaseTitle: '用途から選ぶ', useCaseText: '提供シーンやコース構成に合わせて選べます。', cuisineTitle: '料理ジャンルから選ぶ', cuisineText: '寿司、懐石、和牛、魚介、デザートなどに合わせて探せます。', collectionTitle: '商品一覧', collectionText: '予算、用途、料理、サイズ、色味、MOQ、サンプル可否で絞り込めます。', selectionTitle: '選択リスト / 見積もりカート', sampleTitle: 'サンプル依頼', sampleText: '検討中の商品でサンプル依頼を準備できます。', consultationTitle: 'レストラン相談', consultationText: '店舗コンセプトに合う器選びを相談できます。', contactTitle: '問い合わせ / 見積もり依頼', contactText: '選択リストの商品情報がフォームに反映されます。', detailBack: '商品一覧へ戻る' },
    faq: { q1: 'レストランやホテル向けですか？', a1: 'はい。飲食店、ホテル、購買担当者向けのカタログです。', q2: 'サンプル依頼はできますか？', a2: 'はい。商品カードやサンプル依頼ページから準備できます。', q3: 'MOQは何枚ですか？', a3: '商品や窯元により異なります。各商品カードに目安を表示しています。', q4: '海外配送できますか？', a4: '見積もり時に海外配送をご相談いただけます。', q5: '予算から選べますか？', a5: 'はい。予算別ページとフィルターから選べます。', q6: '料理に合わせた提案はできますか？', a6: 'はい。料理ジャンル別検索や相談ページをご利用ください。', q7: '継続発注に対応できますか？', a7: '安定した調達を見据えてご相談いただけます。', q8: '特注やキュレーションは相談できますか？', a8: 'はい。まとまった数量や店舗全体の選定も相談できます。' },
    footer: { description: '予算、料理、用途、コンセプトから有田焼を選ぶレストラン向けB2Bカタログ。', rights: 'All rights reserved.' },
    valueLabels: { ...Object.fromEntries(Object.entries(valueLabels).map(([group, langs]) => [group, langs.ja])) }
  },
  zh: {
    nav: { home: '首页', useCase: '用途', budget: '预算', cuisine: '菜系', collection: '产品', consultation: '咨询', sampleRequest: '样品申请', faq: 'FAQ', contact: '联系' },
    cta: { requestCatalog: '索取目录', selectionList: '选择清单', browseBudget: '按预算浏览', chooseUseCase: '按用途选择', requestB2B: '索取B2B目录', viewDetails: '查看详情', quickView: '快速查看', addToQuote: '加入询价清单', askSample: '申请样品', requestQuote: '请求报价', discussItems: '咨询这些商品', fullSelection: '查看完整清单', clearAll: '全部清除', submit: '提交请求', startBudget: '按预算浏览', startUseCase: '按用途浏览', catalog: '索取目录', discussConcept: '咨询餐厅概念', budgetRecommendation: '获取预算建议' },
    hero: { kicker: '面向餐厅业主的高级有田烧', title: '按预算、菜系和餐厅概念选择有田烧。', subtitle: '为希望提升摆盘、客人感知和品牌价值的餐厅精选日本高级餐具。', trust1: '适合寿司 / 怀石 / 高级餐厅 / 酒店', trust2: '可咨询样品', trust3: '支持批发与复购' },
    sections: { choose: '按餐厅真正需要的条件选择', chooseText: '从预算、用途、菜系或想营造的体验开始。', useCase: '按用途浏览', budget: '按预算浏览', cuisine: '按菜系浏览', featured: '推荐餐厅用器', challenges: '餐厅业主选择餐具前需要了解的事', value: '餐具如何改变用餐体验', contact: '开始目录、样品或报价咨询', collection: '产品系列', related: '相关产品' },
    cards: { match: '是否匹配菜系和概念？', premium: '能否让菜品更显高级？', reorder: '能否安心复购？', samples: '样品、MOQ和运输如何处理？', authentic: '故事是否足够真实？', matchText: '为寿司、怀石、酒店、品鉴菜单或包间选择合适器皿。', premiumText: '用留白、色彩和层次提升菜品价值感。', reorderText: '为复购、分店和稳定采购做准备。', samplesText: '购买前确认样品、最低订量、运输和交期。', authenticText: '把有田烧的工艺故事融入餐厅品牌。' },
    values: { value1: '让每道菜更具价值感。', value1Text: '选择提升摆盘感知价值的器皿。', value2: '强化餐厅品牌。', value2Text: '让菜单、服务和空间形成一致世界观。', value3: '安心采购。', value3Text: '在承诺前咨询样品、MOQ、国际运输和复购。' },
    product: { bestFor: '适合', moq: 'MOQ', sample: '样品', sampleAvailable: '可申请', sampleRequested: '已选样品', consultation: '可咨询', size: '尺寸', kiln: '窑口 / 产地', price: '价格区间', useCase: '用途', cuisine: '菜系', scene: '推荐场景', shipping: '国际运输咨询', yes: '是', quantity: '数量', unitPrice: '预估单价', estimatedTotal: '预估总额', totalRange: '预估预算', remove: '删除', qty: '数量', added: '已加入', addedNotice: '已加入询价清单。' },
    filter: { title: '筛选', active: '已选筛选', budget: '预算', useCase: '用途', cuisine: '菜系', size: '尺寸', tone: '颜色 / 色调', buyerType: '买家类型', sampleAvailable: '可申请样品', moqRange: 'MOQ范围', upTo12: '最多12件', upTo24: '最多24件', upTo48: '最多48件', sort: '排序', recommended: '推荐', priceLow: '价格从低到高', priceHigh: '价格从高到低', bestSushi: '最适合寿司', bestKaiseki: '最适合怀石', sampleSort: '可申请样品', premiumSort: '高级系列', results: '项结果' },
    cart: { empty: '选择清单为空。', emptyText: '请从预算、菜系或用途开始选择餐具。', title: '选择清单', subtitle: '保存商品、调整数量、申请样品并准备报价。', drawerTitle: '选择清单', subtotal: '预估预算' },
    form: { name: '姓名', company: '餐厅 / 公司名称', country: '国家 / 地区', restaurantType: '餐厅类型', cuisine: '菜系', budget: '单件预算', quantity: '数量范围', selectedItems: '已选商品', sampleRequest: '样品申请', message: '留言', concept: '餐厅概念', spend: '人均消费', opening: '开业 / 采购时间', submitSuccess: '谢谢。您的请求已准备好，我们将审核所选商品并尽快联系您。' },
    page: { budgetTitle: '按预算浏览', budgetText: '查看不同价位适合的餐厅和使用场景。', useCaseTitle: '按用途浏览', useCaseText: '按服务时刻、套餐形式和宾客体验选择。', cuisineTitle: '按菜系浏览', cuisineText: '为寿司、怀石、和牛、海鲜、甜点或清酒搭配寻找器皿。', collectionTitle: '产品系列', collectionText: '按预算、用途、菜系、尺寸、色调、MOQ和样品筛选。', selectionTitle: '选择清单 / 询价车', sampleTitle: '样品申请', sampleText: '为正在考虑的商品准备样品申请。', consultationTitle: '餐厅咨询', consultationText: '告诉我们您的概念，我们会准备餐具方向。', contactTitle: '联系 / 请求报价', contactText: '您的选择清单会自动反映在下方表单。', detailBack: '返回产品列表' },
    faq: { q1: '你们服务餐厅和酒店吗？', a1: '是。本目录专为餐厅、酒店和采购团队设计。', q2: '可以申请样品吗？', a2: '可以。请使用样品按钮或样品申请页面。', q3: 'MOQ是多少？', a3: '取决于商品和窑口，每张商品卡显示起订量。', q4: '可以国际运输吗？', a4: '可在报价过程中咨询国际运输。', q5: '可以按预算选择吗？', a5: '可以。预算页面和筛选器适合按预算规划。', q6: '可以按菜系推荐吗？', a6: '可以。请使用菜系筛选或咨询页面。', q7: '支持复购吗？', a7: '可为稳定运营规划复购。', q8: '可以定制或策划选品吗？', a8: '可以。大型项目可咨询定制或策划。' },
    footer: { description: '面向餐厅业主，按预算、菜系、用途和概念选择有田烧的B2B目录。', rights: 'All rights reserved.' },
    valueLabels: { ...Object.fromEntries(Object.entries(valueLabels).map(([group, langs]) => [group, langs.zh])) }
  },
  fr: {
    nav: { home: 'Accueil', useCase: 'Usage', budget: 'Budget', cuisine: 'Cuisine', collection: 'Collection', consultation: 'Consultation', sampleRequest: 'Échantillons', faq: 'FAQ', contact: 'Contact' },
    cta: { requestCatalog: 'Demander le catalogue', selectionList: 'Liste de sélection', browseBudget: 'Par budget', chooseUseCase: 'Par usage', requestB2B: 'Catalogue B2B', viewDetails: 'Voir détails', quickView: 'Aperçu', addToQuote: 'Ajouter au devis', askSample: 'Demander échantillon', requestQuote: 'Demander devis', discussItems: 'Discuter ces pièces', fullSelection: 'Voir la liste complète', clearAll: 'Tout effacer', submit: 'Envoyer', startBudget: 'Par budget', startUseCase: 'Par usage', catalog: 'Demander catalogue', discussConcept: 'Discuter le concept', budgetRecommendation: 'Recommandation par budget' },
    hero: { kicker: 'Arita haut de gamme pour restaurants', title: 'Choisissez la porcelaine Arita par budget, cuisine et concept.', subtitle: 'Vaisselle japonaise premium pour élever le dressage, la perception client et la valeur de marque.', trust1: 'Pour sushi / kaiseki / fine dining / hôtels', trust2: 'Échantillons sur demande', trust3: 'Grossiste et réassort possibles' },
    sections: { choose: 'Choisir selon les besoins du restaurant', chooseText: 'Commencez par le budget, l’usage, la cuisine ou l’atmosphère souhaitée.', useCase: 'Par usage', budget: 'Par budget', cuisine: 'Par cuisine', featured: 'Pièces recommandées', challenges: 'Ce que les restaurateurs doivent savoir avant de choisir', value: 'Pourquoi la vaisselle change l’expérience', contact: 'Commencer par catalogue, échantillon ou devis', collection: 'Collection', related: 'Produits associés' },
    cards: { match: 'Convient-elle au concept ?', premium: 'Rend-elle le plat plus premium ?', reorder: 'Peut-on réassortir sereinement ?', samples: 'Comment fonctionnent échantillons, MOQ et livraison ?', authentic: 'L’histoire est-elle authentique ?', matchText: 'Trouvez des pièces pour sushi, kaiseki, hôtels, menus dégustation ou salons privés.', premiumText: 'Utilisez espace, couleur et relief pour valoriser chaque plat.', reorderText: 'Planifiez réassorts, nouvelles adresses et sourcing stable.', samplesText: 'Clarifiez échantillons, quantités minimales, livraison et délais.', authenticText: 'Intégrez le récit artisanal d’Arita à votre marque.' },
    values: { value1: 'Rendre chaque plat plus précieux.', value1Text: 'Choisir une vaisselle qui augmente la valeur perçue.', value2: 'Renforcer la marque du restaurant.', value2Text: 'Créer une cohérence entre menu, service et salle.', value3: 'S’approvisionner avec confiance.', value3Text: 'Discuter échantillons, MOQ, livraison internationale et réassort.' },
    product: { bestFor: 'Idéal pour', moq: 'MOQ', sample: 'Échantillon', sampleAvailable: 'Disponible', sampleRequested: 'Échantillon demandé', consultation: 'Consultation possible', size: 'Taille', kiln: 'Four / Origine', price: 'Prix', useCase: 'Usage', cuisine: 'Cuisine', scene: 'Scène recommandée', shipping: 'Livraison internationale', yes: 'Oui', quantity: 'Quantité', unitPrice: 'Prix unitaire estimé', estimatedTotal: 'Total estimé', totalRange: 'Budget estimé', remove: 'Retirer', qty: 'Qté', added: 'Ajouté', addedNotice: 'ajouté à la liste de devis.' },
    filter: { title: 'Filtres', active: 'Filtres actifs', budget: 'Budget', useCase: 'Usage', cuisine: 'Cuisine', size: 'Taille', tone: 'Couleur / Ton', buyerType: 'Type d’acheteur', sampleAvailable: 'Échantillon disponible', moqRange: 'MOQ', upTo12: 'Jusqu’à 12 pièces', upTo24: 'Jusqu’à 24 pièces', upTo48: 'Jusqu’à 48 pièces', sort: 'Trier', recommended: 'Recommandé', priceLow: 'Prix croissant', priceHigh: 'Prix décroissant', bestSushi: 'Idéal sushi', bestKaiseki: 'Idéal kaiseki', sampleSort: 'Échantillon disponible', premiumSort: 'Collection premium', results: 'résultats' },
    cart: { empty: 'Votre liste est vide.', emptyText: 'Commencez par budget, cuisine ou usage.', title: 'Liste de sélection', subtitle: 'Sauvez des pièces, ajustez les quantités, demandez des échantillons.', drawerTitle: 'Votre liste', subtotal: 'Budget estimé' },
    form: { name: 'Nom', company: 'Restaurant / Société', country: 'Pays / Région', restaurantType: 'Type de restaurant', cuisine: 'Cuisine', budget: 'Budget par pièce', quantity: 'Quantité', selectedItems: 'Articles sélectionnés', sampleRequest: 'Demande d’échantillon', message: 'Message', concept: 'Concept du restaurant', spend: 'Ticket moyen', opening: 'Calendrier d’achat', submitSuccess: 'Merci. Votre demande est prête. Notre équipe examinera votre sélection et vous contactera bientôt.' },
    page: { budgetTitle: 'Par budget', budgetText: 'Choisissez une gamme de prix et son usage opérationnel.', useCaseTitle: 'Par usage', useCaseText: 'Choisissez selon le moment de service et l’expérience.', cuisineTitle: 'Par cuisine', cuisineText: 'Trouvez les pièces pour sushi, kaiseki, wagyu, fruits de mer, dessert ou saké.', collectionTitle: 'Collection', collectionText: 'Filtrez par budget, usage, cuisine, taille, ton, MOQ et échantillon.', selectionTitle: 'Liste / Panier de devis', sampleTitle: 'Demande d’échantillon', sampleText: 'Préparez une demande d’échantillon.', consultationTitle: 'Consultation restaurant', consultationText: 'Décrivez votre concept pour recevoir une direction.', contactTitle: 'Contact / Devis', contactText: 'Vos articles sélectionnés sont repris ci-dessous.', detailBack: 'Retour collection' },
    faq: { q1: 'Travaillez-vous avec restaurants et hôtels ?', a1: 'Oui. Ce catalogue est conçu pour restaurants, hôtels et équipes achats.', q2: 'Peut-on demander des échantillons ?', a2: 'Oui. Utilisez le bouton échantillon ou la page dédiée.', q3: 'Quel est le MOQ ?', a3: 'Le MOQ dépend de l’article et du four. Chaque carte l’indique.', q4: 'Livrez-vous à l’international ?', a4: 'La livraison internationale peut être discutée lors du devis.', q5: 'Peut-on choisir par budget ?', a5: 'Oui. Les filtres et la page budget sont prévus pour cela.', q6: 'Recommandez-vous selon la cuisine ?', a6: 'Oui. Utilisez les filtres cuisine ou la consultation.', q7: 'Assurez-vous les réassorts ?', a7: 'Les réassorts peuvent être planifiés.', q8: 'Peut-on discuter de sélections sur mesure ?', a8: 'Oui. Les projets sur mesure sont possibles.' },
    footer: { description: 'Catalogue B2B pour choisir Arita par budget, cuisine, usage et concept.', rights: 'All rights reserved.' },
    valueLabels: { ...Object.fromEntries(Object.entries(valueLabels).map(([group, langs]) => [group, langs.fr])) }
  },
  es: {
    nav: { home: 'Inicio', useCase: 'Uso', budget: 'Presupuesto', cuisine: 'Cocina', collection: 'Colección', consultation: 'Consulta', sampleRequest: 'Muestras', faq: 'FAQ', contact: 'Contacto' },
    cta: { requestCatalog: 'Solicitar catálogo', selectionList: 'Lista de selección', browseBudget: 'Por presupuesto', chooseUseCase: 'Por uso', requestB2B: 'Catálogo B2B', viewDetails: 'Ver detalles', quickView: 'Vista rápida', addToQuote: 'Añadir a cotización', askSample: 'Pedir muestra', requestQuote: 'Solicitar cotización', discussItems: 'Consultar estos artículos', fullSelection: 'Ver lista completa', clearAll: 'Borrar todo', submit: 'Enviar solicitud', startBudget: 'Por presupuesto', startUseCase: 'Por uso', catalog: 'Solicitar catálogo', discussConcept: 'Consultar concepto', budgetRecommendation: 'Recomendación por presupuesto' },
    hero: { kicker: 'Arita premium para restaurantes', title: 'Elija Arita por presupuesto, cocina y concepto.', subtitle: 'Vajilla japonesa premium para elevar el emplatado, la percepción del cliente y el valor de marca.', trust1: 'Para sushi / kaiseki / fine dining / hoteles', trust2: 'Consulta de muestras disponible', trust3: 'Mayorista y reposición disponibles' },
    sections: { choose: 'Elija según lo que importa al restaurante', chooseText: 'Empiece por presupuesto, uso, cocina o atmósfera deseada.', useCase: 'Por uso', budget: 'Por presupuesto', cuisine: 'Por cocina', featured: 'Piezas recomendadas', challenges: 'Lo que debe saber antes de elegir vajilla', value: 'Por qué la vajilla cambia la experiencia', contact: 'Comience con catálogo, muestra o cotización', collection: 'Colección', related: 'Productos relacionados' },
    cards: { match: '¿Encaja con la cocina y el concepto?', premium: '¿Hace que el plato se vea más premium?', reorder: '¿Podemos reponer con confianza?', samples: '¿Cómo funcionan muestras, MOQ y envío?', authentic: '¿La historia es auténtica?', matchText: 'Encuentre piezas para sushi, kaiseki, hoteles, menús degustación o privados.', premiumText: 'Use espacio, color y altura para elevar cada plato.', reorderText: 'Planifique reposiciones, nuevas sedes y suministro estable.', samplesText: 'Aclare muestras, mínimos, envíos y plazos antes de comprar.', authenticText: 'Integre la artesanía de Arita en la marca del restaurante.' },
    values: { value1: 'Hacer que cada plato parezca más valioso.', value1Text: 'Seleccione vajilla que eleve el valor percibido.', value2: 'Fortalecer la marca del restaurante.', value2Text: 'Cree coherencia entre menú, servicio y sala.', value3: 'Comprar con confianza.', value3Text: 'Consulte muestras, MOQ, envío internacional y reposición.' },
    product: { bestFor: 'Ideal para', moq: 'MOQ', sample: 'Muestra', sampleAvailable: 'Disponible', sampleRequested: 'Muestra solicitada', consultation: 'Consulta disponible', size: 'Tamaño', kiln: 'Horno / Origen', price: 'Rango de precio', useCase: 'Uso', cuisine: 'Cocina', scene: 'Escena recomendada', shipping: 'Consulta de envío internacional', yes: 'Sí', quantity: 'Cantidad', unitPrice: 'Precio unitario estimado', estimatedTotal: 'Total estimado', totalRange: 'Presupuesto estimado', remove: 'Eliminar', qty: 'Cant.', added: 'Añadido', addedNotice: 'añadido a la lista de cotización.' },
    filter: { title: 'Filtros', active: 'Filtros activos', budget: 'Presupuesto', useCase: 'Uso', cuisine: 'Cocina', size: 'Tamaño', tone: 'Color / Tono', buyerType: 'Tipo de comprador', sampleAvailable: 'Muestra disponible', moqRange: 'MOQ', upTo12: 'Hasta 12 piezas', upTo24: 'Hasta 24 piezas', upTo48: 'Hasta 48 piezas', sort: 'Ordenar', recommended: 'Recomendado', priceLow: 'Precio: menor a mayor', priceHigh: 'Precio: mayor a menor', bestSushi: 'Ideal para sushi', bestKaiseki: 'Ideal para kaiseki', sampleSort: 'Muestra disponible', premiumSort: 'Colección premium', results: 'resultados' },
    cart: { empty: 'La lista está vacía.', emptyText: 'Empiece eligiendo vajilla por presupuesto, cocina o uso.', title: 'Lista de selección', subtitle: 'Guarde artículos, ajuste cantidades, pida muestras y prepare una cotización.', drawerTitle: 'Su lista', subtotal: 'Presupuesto estimado' },
    form: { name: 'Nombre', company: 'Restaurante / Empresa', country: 'País / Región', restaurantType: 'Tipo de restaurante', cuisine: 'Cocina', budget: 'Presupuesto por pieza', quantity: 'Rango de cantidad', selectedItems: 'Artículos seleccionados', sampleRequest: 'Solicitud de muestra', message: 'Mensaje', concept: 'Concepto del restaurante', spend: 'Ticket medio', opening: 'Fecha de apertura / compra', submitSuccess: 'Gracias. Su solicitud está preparada. Nuestro equipo revisará los artículos y le contactará pronto.' },
    page: { budgetTitle: 'Por presupuesto', budgetText: 'Seleccione un rango de precio y vea dónde funciona mejor.', useCaseTitle: 'Por uso', useCaseText: 'Elija por momento de servicio y experiencia del cliente.', cuisineTitle: 'Por cocina', cuisineText: 'Encuentre piezas para sushi, kaiseki, wagyu, mariscos, postre o sake.', collectionTitle: 'Colección', collectionText: 'Filtre por presupuesto, uso, cocina, tamaño, tono, MOQ y muestra.', selectionTitle: 'Lista / Carrito de cotización', sampleTitle: 'Solicitud de muestra', sampleText: 'Prepare una solicitud para las piezas que considera.', consultationTitle: 'Consulta de restaurante', consultationText: 'Cuéntenos su concepto y prepararemos una dirección.', contactTitle: 'Contacto / Cotización', contactText: 'Sus artículos seleccionados aparecen abajo.', detailBack: 'Volver a colección' },
    faq: { q1: '¿Trabajan con restaurantes y hoteles?', a1: 'Sí. Este catálogo es para restaurantes, hoteles y compras.', q2: '¿Podemos pedir muestras?', a2: 'Sí. Use el botón de muestra o la página de muestras.', q3: '¿Cuál es el MOQ?', a3: 'Depende del artículo y del horno. Cada tarjeta muestra la cantidad inicial.', q4: '¿Envían internacionalmente?', a4: 'El envío internacional se consulta durante la cotización.', q5: '¿Podemos elegir por presupuesto?', a5: 'Sí. La página y filtros de presupuesto ayudan a planificar.', q6: '¿Recomiendan según cocina?', a6: 'Sí. Use filtros de cocina o la consulta.', q7: '¿Soportan reposiciones?', a7: 'Las reposiciones pueden planificarse.', q8: '¿Podemos hablar de selecciones a medida?', a8: 'Sí. Las selecciones curadas o a medida son posibles.' },
    footer: { description: 'Catálogo B2B para elegir Arita por presupuesto, cocina, uso y concepto.', rights: 'All rights reserved.' },
    valueLabels: { ...Object.fromEntries(Object.entries(valueLabels).map(([group, langs]) => [group, langs.es])) }
  }
};
